### ISSUE TITLE
Thunar theme?

### ISSUE THREAD

**Issue by ghost** [drahenprofi/dotfiles#2]
where can I get the thunar theme?

**Comment by drahenprofi** [comment]
You can install my GTK theme by copying the `.themes/Arc-Horizon` folder into the `.themes` folder in your home directory. There I made some small adjustments to thunars overall look ([this file](https://github.com/arndtphillip/dotfiles/blob/master/.themes/Arc-Horizon/gtk-3.0/custom.css)). The bar on the left is an awesome wm titlebar, it is implemented [here](https://github.com/arndtphillip/dotfiles/blob/master/.config/awesome/decorations/thunar.lua)

**Comment by ghost** [comment]
thanks, im new to this.
