### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by RancidRocket** [drahenprofi/dotfiles#3]
I have tries putting the .icons folder in the home directory, i have tried putting it in /usr/share/icons (renaming the folder so it isn't hidden there). and for the life of me i cannot get the icons to show. Where am i supposed to put them?
![example](https://user-images.githubusercontent.com/55551848/104812744-076acd80-5850-11eb-8756-d48f7d8f4d9f.png)

**Comment by drahenprofi** [comment]
Additionally you need to install the Fira Mono Nerd Fonts (`nerd-fonts-fira-mono` in the AUR if you are on Arch Linux).

**Comment by RancidRocket** [comment]
ahh, i'll install that now. i forgot about that one funnily enough

**Comment by RancidRocket** [comment]
This worked, Thank you!!! Now i just need to find where the keybinds are, and change some few things and i'll be set! Thank you!
