### ISSUE TITLE
What is "sp" in the README?

### ISSUE THREAD

**Issue by koolskateguy89** [drahenprofi/dotfiles#4]
Does ```sp``` mean ```spicetify```?

**Comment by drahenprofi** [comment]
No, it's a [small utility script](https://gist.github.com/wandernauta/6800547), which pulls data from running spotify instances. It is used to display the currently playing song in the topbar. 
You can install it from the AUR if you are on Arch: [https://aur.archlinux.org/packages/sp/](https://aur.archlinux.org/packages/sp/)

**Comment by koolskateguy89** [comment]
I see thank you
