### ISSUE TITLE
How to disable widgets?

### ISSUE THREAD

**Issue by xynydev** [drahenprofi/dotfiles#6]
First of all, thank you for making this. Ever since I fell in love with the horizon theme I have been searching for a GTK theme and something for AwesomeWM (my main window manager) is a great plus.

But if I want to disable some of the widgets like the dock how would I go about doing that? 
I have tried commenting the require lines in `rc.lua` but that didn't work and I've tried looking through the files for other places where the widgets are called, but with no luck.

**Comment by drahenprofi** [comment]
I rewrote the dock and didn't delete the old files. The new name is `tasklist`. To disable it you have to comment `require("widgets.tasklist")` in `rc.lua`.

**Comment by xynydev** [comment]
Great, thanks. That worked!
