### ISSUE TITLE
workability with dual monitor

### ISSUE THREAD

**Issue by budweisserr** [drahenprofi/dotfiles#8]
lots of features just dont work. also windows do not shown at all with 2 monitors. tasklist, windows, widgets, pop-ups and so on just have very strange behaviour. did you test it with two monitors?

**Comment by drahenprofi** [comment]
I'm sorry, I only have a single monitor, so that's what the setup is for. You could certainly modify it to work on 2 monitors, but it would require some changes.

**Comment by budweisserr** [comment]
i thought u also tried setup for 2+ monitors, but thats ok. still setup is perfect. i`ll try to change config. thanks!
